### ISSUE TITLE
Battery temperature sensor

### ISSUE THREAD

**Issue by bsg-marvin** [StealthChesnut/HA-FoxESS-Modbus#1]
I believe I have managed to find which one is for battery temperature:

    - name: "Battery temperature"
      scan_interval: 60
      slave: 247
      address: 11038
      state_class: measurement
      unit_of_measurement: "°C"
      scale: 0.1
      data_type: int16
      input_type: input
      device_class: battery

**Comment by williamjeccles** [comment]
Nice, what about grid use vs export so we can drive automation when we're exporting?

**Comment by bsg-marvin** [comment]
> 

Will try to play a little more over the next few days. :)

**Comment by StealthChesnut** [comment]
Added the sensor - thanks @bsg-marvin !
