### ISSUE TITLE
Instructions for connecting W610 to Ethernet

### ISSUE THREAD

**Issue by canton7** [StealthChesnut/HA-FoxESS-Modbus#106]
Hi,

After some tinkering, I managed to get my W610 connected using ethernet, rather than as a wifi client.

I don't have permission to edit the wiki, but I've created some instructions below in case you (or anyone else) finds them useful.

Thanks!

1. Plug in the USR W610 into power **without an ethernet cable attached** wait 10-15 secs to boot
1. Using a laptop or desktop with wifi access search for and connect to the device’s wifi name. Normally USR-XXXX
1. Open a browser and navigate to 10.10.100.254 (normally printed on the back of the device)
1. Enter **Admin / Admin** for the username and Password
1. Click english top right to change to english
1. Under **Ethernet Setting** - Set the Ethernet work mode to WAN port, Apply
1. Under **Mode Selection** - Set AP Mode, Data Transfer Mode to Modbus TCP<=>Modbus RTU, Apply
1. Under **STA Interface Setting** - Set AP+STA to Off, Apply
1. Under **Device Management** - Click Restart, and connect an ethernet cable

Using your router's device list or local ip scanner, find the ip address of the USR now on your local network.

1. Type in your USR’s IP address while connected to your normal network
1. When prompted enter Admin/Admin as the username and password
1. Under **AP Interface Setting** - change Security Mode from Disable to WPA2-PSK and set a Pass Phase in the box, this will secure the wifi for the device but allow you future direct access for future troubleshooting
1. Under **Application Settings** Match These settings (Click Apply after each section and then click Application Settings for each, no need to reboot until you've completed them all):

**Comment by StealthChesnut** [comment]
Thanks for the info! I've added it to the wiki page.
