### ISSUE TITLE
battery to grid control? 

### ISSUE THREAD

**Issue by dbrb2** [StealthChesnut/HA-FoxESS-Modbus#28]
This is more a query than a fault....does the modbus interface allow local control of whether the inverter is charging from the grid, or supplying to the grid...or is it read-only? 

Cheers!

**Comment by StealthChesnut** [comment]
The interface on the inverter might allow for control, but there's currently no easy (safe?) way to figure that out. Fox won't respond to requests for the modbus specification, 

It's possible to read data and figure out what it's doing, but it's much more difficult/impossible to know what should be sent to change the mode.

For the time being this integration will be read-only, unless we can get hold of the proper documentation / safe method to work with setting modes. Hope that's understandable. 👍
