### ISSUE TITLE
CT2 Lan address

### ISSUE THREAD

**Issue by delibury** [StealthChesnut/HA-FoxESS-Modbus#42]
The LAN address for CT2 is 31015.

When using CT2 for PV power, load_power reads negative when exporting.
Please add the following templates to correct this.

ct2_power:
          friendly_name: "CT 2 Power"
          unit_of_measurement: 'kW'
          device_class: power
          value_template: >
            {{ [0, (states('sensor.ct2_meter') | float(default=0)  * 1)]|max }}

house_power:
          friendly_name: "House Power"
          unit_of_measurement: 'kW'
          device_class: power
          value_template: >
            {% set load = states('sensor.load_power') | float(default=0) %}
            {% set ct2 = states('sensor.ct2_meter') | float(default=0) %}
            {% set power = ( load + ct2 ) | round(3) %}
            {{ "{:.3f}".format(power) }}

Cheers!

**Comment by rand12345** [comment]
Hi,

I have an issue with this enhancement. HA is reporting 0 (zero) for CT2 on 31050 but is reported correctly in the FoxCloud app.

Any assistance would be appreciated. 

foxmodbus.yaml
```
    - name: "CT2 Meter"
      scan_interval: 5
      address: 31015
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.001
      precision: 3
      input_type: holding    
      device_class: power
```

configuration.yaml

```
      ct2_power:
          friendly_name: "CT 2 Power"
          unit_of_measurement: 'kW'
          device_class: power
          value_template: >
            {{ [0, (states('sensor.ct2_meter') | float(default=0) * 1)]|max }}

      house_power:
          friendly_name: "House Power"
          unit_of_measurement: 'kW'
          device_class: power
          value_template: >
            {% set load = states('sensor.load_power') | float(default=0) %}
            {% set ct2 = states('sensor.ct2_meter') | float(default=0) %}
            {% set power = ( load + ct2 ) | round(3) %}
            {{ "{:.3f}".format(power) }}
```

FoxESS 5.0 AC

Master 1.48
Slave 1.02
Manager 1.45

**Comment by StealthChesnut** [comment]
If you go into the Developer Tools section of HomeAssistant, then look at States, can you find the ct2_meter sensor? does it show a value in there?

**Comment by StealthChesnut** [comment]
What is in your configuration.yaml file for the modbus include line? 

Is it referencing your file foxmodbus.yaml or a different file? that's not the filename I'm expecting for your sensor definitions.

**Comment by rand12345** [comment]
Well spotted. I was alternating between configs so as not to disturb the repo version. 

All working with `House Power` behaving as expected, thank you for your help.

**Comment by williamjeccles** [comment]
Created a pull request for this change to be merged for the LAN modbus https://github.com/StealthChesnut/HA-FoxESS-Modbus/pull/83
