### ISSUE TITLE
Question about sensor update frequency

### ISSUE THREAD

**Issue by benbeton** [StealthChesnut/HA-FoxESS-Modbus#79]
I have set my sensors with a scan_interval of 5 - 30 sec. However, the values update very differently, often there are some minutes no update, sometimes even up to 25 min. although the values change with the cloud integration very fast. 

But since I prefer the solution via Modbus, I would like to find out if this is a normal behavior or if it can be due to a misconfiguration. Here are a few examples. In this case, there was bright sunshine and the battery was charging at about 3 - 4 KW, so the SoC sensor should have changed promptly, but instead there are jumps of ~20%. 

**My setup**
- FoxESS Inverter H3 6.0E 6.5KW Battery
- USR-610 Modbus LAN converter

**SoC charge state screenshots:**
<img width="560" alt="Screenshot_2023-01-17 11 31 39_b2f7MH" src="https://user-images.githubusercontent.com/1405209/212999477-b7d4f152-215c-46d6-8ea1-11d388102f58.png">
<img width="564" alt="Screenshot_2023-01-17 11 10 03_KDudbV" src="https://user-images.githubusercontent.com/1405209/212999487-a850c6ad-2448-4a6b-b947-73059b9e348c.png">
<img width="566" alt="Screenshot_2023-01-17 10 52 20_UboAcO" src="https://user-images.githubusercontent.com/1405209/212999491-2c9ca7b8-05de-4ce4-b155-a9cfc1455d31.png">

**SoC sensor config:**
```
- name: "fox_bat_soc"
    scan_interval: 30
    slave: 247
    address: 31038
    state_class: measurement
    unit_of_measurement: "%"
    data_type: uint16
    input_type: holding
    device_class: battery
```

**Modbus config**
```
- name: FoxESS_Inverter
  type: tcp
  host: 192.168.XX.XXX
  port: 502
  retry_on_empty: true
  retries: 3
  timeout: 5
  close_comm_on_error: false
```

in the same time template sensor (pv1_power & pv2_power) has delivered timely data:

<img width="563" alt="Screenshot_2023-01-17 11 18 39_86Y794" src="https://user-images.githubusercontent.com/1405209/213000519-d2515045-e63e-4b54-a779-871f554be0c9.png">
<img width="549" alt="Screenshot_2023-01-17 10 57 16_duiaxh" src="https://user-images.githubusercontent.com/1405209/213000522-906a6915-ad27-4b6d-add0-828c89f4fa44.png">

so it looks like the inverter is providing data but very different in time, is there any explanation or way to change this?
I would like to have as accurate data as possible

regards

**Comment by williamjeccles** [comment]
What poll rate do you have set on the USR converter? Likely HA is asking the USR for updates every 30 seconds but the modbus settings on the USR are set with a slower polling rate.

**Comment by benbeton** [comment]
this is my current polling config on the USR:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/1405209/216519927-114fdfcd-9f9a-40bf-80a2-8331f231a133.png">
