### ISSUE TITLE
sensors error -slave247

### ISSUE THREAD

**Issue by SteveBrailsord** [StealthChesnut/HA-FoxESS-Modbus#91]
a number of sensors in the modbusLAN.yaml,  don't have the line"   slave: 247  "
these sensors don't seem to work without it ?

You need to add the line then reboot the system (a restart isn't good enough)

**Comment by williamjeccles** [comment]
Hey @SteveBrailsord please submit a pull request and we can merge the change in.

**Comment by SteveBrailsord** [comment]
Sorry I don’t know what that is ?
I’ve manually updated my config?
