### ISSUE TITLE
W610 setup with HA

### ISSUE THREAD

**Issue by Frith123** [StealthChesnut/HA-FoxESS-Modbus#96]
Greetings!

Having an issue with setting up the w610 connected to a H1 inverter with a wired home network. Successfully followed the guide Stealth-chestnut created on here and the wiki article and received data from the H1 for several days. However it has moments of dropping out, and then no data is received intermittently. 
To add to it on the network there is also a google mesh setup installed which seems to be causing somekind of "fight" between the w610 ip series addresses and the ip addresses assigned by the Mesh router.
The w610 is connected directly to n ethernet over power adapter then into a switch(hub) and then from there into the google mesh router.
Running an Ip scanner brings up several W610(s) and also  the ip address series 10.10.100.. ect of the w610 gets assigned to some of the other devices on the network(tv, hue lighting system). Pretty lost on this one, and believe I need to start over again. 
Wondering if someone has a guide for a ethernet wired setup of the 610? (I believe the link to wiki for setting up the w610 is for a wireless setup(which I cannot do due to distance from the inverter to the network hub)
Apologies that this is more of a network configuration issue(which I am unfamiliar with). Any help would be appreciated.

**Comment by williamjeccles** [comment]
You'll need to update the LAN addresses or DHCP settings. Better to ask this question under the discussions area of this project than as a issue.
